window.STATUS = {
    PENDING_STAMP: 1,
    STAMPED: 2,
    ADMIN_PROCESS: 3,
    WAITING_SIGNATURE: 3.5,
    SIGNED: 4,
    SENT: 5,
    MANAGER_SIGNATURE: 6,
    MANAGER_SENT: 7,
    BAILIFF_SIGNATURE: 8,
    BAILIFF_SENT: 9,
    MAYOR1_SIGNATURE: 10,
    MAYOR1_SENT: 11,
    MAYOR2_SIGNATURE: 12,
    MAYOR2_SENT: 13,
    DIRECTORY: 14,
    ARCHIVED: 15
};